[package]
name = "linttex"
version = "0.1.0"
authors = ["Kye Shi <shi.kye@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = '0.3.21'
thiserror = '1.0.25'
anyhow = '1.0.40'
console = '0.14.1'
